apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Enable web-terminal
  exec.enabled: "true"
  # add an additional local user with apiKey and login capabilities
  #   apiKey - allows generating API keys
  #   login - allows to login using UI
  # disables user. User is enabled by default
  # accounts.alice.enabled: "false"
  #
  # Template Existing ODIC config
  #
  url: https://test-platform.costellomedicalapps.com/
  oidc.config: |
    name: Azure 
    issuer: https://login.microsoftonline.com/eb09cf74-5927-45cd-b9ca-b00d5c677f0e/v2.0
    clientID: db593be3-6418-4fca-bff0-c0a416ecbe07
    clientSecret: $oidc.azure.clientSecret 
    requestedIDTokenClaims:
      email:
        essential: true
    requestedScopes:
      - openid
      - profile
      - email

